# Basic Operations on Images[링크](https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_core/py_basic_ops/py_basic_ops.html#basic-ops)
* Learn to read and edit pixel values, working with image ROI and other basic operations.

## Goal

Learn to:

* Access pixel values and modify them
* Access image properties
* Setting Region of Image (ROI)
* Splitting and Merging images

Almost all the operations in this section is mainly related to Numpy rather than OpenCV. A good knowledge of Numpy is required to write better optimized code with OpenCV.

( Examples will be shown in Python terminal since most of them are just single line codes )

In [1]:
import cv2
import numpy as np

img = cv2.imread('messi5.png')

px = img[100, 100]
print(px)

blue = img[100, 100, 0]
print(blue)

img[100,100] = [1,2,3]

px = img[100, 100]
print(px)

print(img.item(100, 100, 0))

img.itemset((100, 100, 0), 10)
img.itemset((100, 100, 1), 20)
img.itemset((100, 100, 2), 30)
print(img[100, 100])

print(img.shape)
print(img.size)
print(img.dtype)

logo = img[0:100, 0:100]
img[200:300, 200:300] = logo

#b, g, r = cv2.split(img)
#img = cv2.merge((r, g, b))
#b = img[100:200, 100:200, 1]
#img[:, :, 2] = 0

cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[204 204 204]
204
[1 2 3]
1
[10 20 30]
(364, 672, 3)
733824
uint8


## Making Borders for Images (Padding)

In [2]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

BLUE = [255,0,0]

img1 = cv2.imread('opencv_logo.png')

#replicate = cv2.copyMakeBorder(img1,10,10,10,10,cv2.BORDER_REPLICATE)
#reflect = cv2.copyMakeBorder(img1,10,10,10,10,cv2.BORDER_REFLECT)
#reflect101 = cv2.copyMakeBorder(img1,10,10,10,10,cv2.BORDER_REFLECT_101)
#wrap = cv2.copyMakeBorder(img1,10,10,10,10,cv2.BORDER_WRAP)
#constant= cv2.copyMakeBorder(img1,10,10,10,10,cv2.BORDER_CONSTANT,value=BLUE)

#plt.subplot(231),plt.imshow(img1,'gray'),plt.title('ORIGINAL')
#plt.subplot(232),plt.imshow(replicate,'gray'),plt.title('REPLICATE')
#plt.subplot(233),plt.imshow(reflect,'gray'),plt.title('REFLECT')
#plt.subplot(234),plt.imshow(reflect101,'gray'),plt.title('REFLECT_101')
#plt.subplot(235),plt.imshow(wrap,'gray'),plt.title('WRAP')
#plt.subplot(236),plt.imshow(constant,'gray'),plt.title('CONSTANT')

#plt.show()