### [Arithmetic Operations on Images](https://docs.opencv.org/3.4/d0/d86/tutorial_py_image_arithmetics.html)
Perform arithmetic operations on images

#### Goal
* Learn several arithmetic operations on images like addition, subtraction, bitwise operations etc.
* You will learn these functions : [cv.add()](https://docs.opencv.org/3.4/d2/de8/group__core__array.html#ga10ac1bfb180e2cfda1701d06c24fdbd6), [cv.addWeighted()](https://docs.opencv.org/3.4/d2/de8/group__core__array.html#gafafb2513349db3bcff51f54ee5592a19) etc.

#### Image Addition
You can add two images by OpenCV function, cv.add() or simply by numpy operation, res = img1 + img2. Both images should be of same depth and type, or second image can just be a scalar value.

> **Note** There is a difference between OpenCV addition and Numpy addition. OpenCV addition is a saturated operation while Numpy addition is a modulo operation.

For example, consider below sample:

In [1]:
import cv2 as cv
import numpy as np
import sys
sys.path.insert(0, '../common')
import bonghanUtil as u

x = np.uint8([250]) 
y = np.uint8([10])

print(cv.add(x, y)) # 256 + 10 = 260 => 255
print(x + y)        # 256 + 10 = 260 % 256 = 4

[[255]]
[4]


It will be more visible when you add two images. OpenCV function will provide a better result. So always better stick to OpenCV functions.

#### Image Blending
This is also image addition, but different weights are given to images so that it gives a feeling of blending or transparency. Images are added as per the equation below:

$$ g(x) = (1 - \alpha)f_{0}(x) + \alpha f_{1}(x) $$

By varying α from \\( 0 \rightarrow 1 \\), you can perform a cool transition between one image to another.

Here I took two images to blend them together. First image is given a weight of 0.7 and second image is given 0.3. cv.addWeighted() applies following equation on the image.


$$ dst = \alpha \cdot img1 + \beta \cdot img2 + \gamma $$
Here \\( \gamma \\) is taken as zero

cv.resize(img, None, fx = 0.5, fy = 0.5, interpolation = cv.INTER_AREA)  
cv.resize(img, (width * 2, height * 2) , interpolation = cv.INTER_CUBIC)  
cv.resize(img, None, fx = 2, fy = 2    , interpolation = cv.INTER_CUBIC)  

In [2]:
img1 = cv.imread('../data/ml.png')
img2 = cv.imread('../data/opencv-logo.png')

img1 = cv.resize(img1, (500, 500), interpolation = cv.INTER_CUBIC)
img2 = cv.resize(img2, (500, 500), interpolation = cv.INTER_CUBIC)

dst  = cv.addWeighted(img1, 0.7, img2, 0.3, 0)

u.showImage(dst)

![](imageMerge.jpg)


[260:263, 260:263, :]

img1           img2           dst
[[[195 230 255][[[255 255 255][[[213 238 255]
  [204 236 255]  [255 255 255]  [219 242 255]
  [211 241 255]  [255 255 255]  [224 245 255]]]]

 [[163 217 255] [[255 255 255] [[191 228 255]
  [163 213 255]  [255 255 255]  [191 226 255]
  [156 202 250]  [255 255 255]  [186 218 252]]]]

 [[144 209 255] [[255 255 255] [[177 223 255]
  [131 190 247]  [255 255 255]  [168 210 249]
[100 155 219]]]  [255 255 255]]][146 185 230]]]

#### Bitwise Operations
This includes bitwise AND, OR, NOT and XOR operations. They will be highly useful while extracting any part of the image (as we will see in coming chapters), defining and working with non-rectangular ROI etc. Below we will see an example on how to change a particular region of an image.

I want to put OpenCV logo above an image. If I add two images, it will change color. If I blend it, I get an transparent effect. But I want it to be opaque. If it was a rectangular region, I could use ROI as we did in last chapter. But OpenCV logo is a not a rectangular shape. So you can do it with bitwise operations as below:

In [2]:
img1 = cv.imread('../data/messi5.jpg')
img2 = cv.imread('../data/opencv-logo-white.png')

rows, cols, channels = img2.shape
roi = img1[0:rows, 0:cols ]

img2gray = cv.cvtColor(img2, cv.COLOR_BGR2GRAY)
u.showImage(img2gray)

ret, mask = cv.threshold(img2gray, 10, 255, cv.THRESH_BINARY)
u.showImage(mask)

mask_inv = cv.bitwise_not(mask)
u.showImage(mask_inv)

img1_bg = cv.bitwise_and(roi, roi, mask = mask_inv)
u.showImage(img1_bg)

# Take only region of logo from logo image.
img2_fg = cv.bitwise_and(img2, img2, mask = mask)
u.showImage(img2_fg)

# Put logo in ROI and modify the main image
dst = cv.add(img1_bg,img2_fg)
u.showImage(dst)

img1[0:rows, 0:cols ] = dst
u.showImage(img1)

![](dstImage.jpg)
roi와 img1과 add하면 결과 처럼 나오지 않는다.

#### Additional Resources

#### Exercises
1. Create a slide show of images in a folder with smooth transition between images using [cv.addWeighted()](https://docs.opencv.org/3.4/d2/de8/group__core__array.html#gafafb2513349db3bcff51f54ee5592a19) function

In [35]:
import cv2 as cv
import numpy as np
import sys
sys.path.insert(0, '../common')
import bonghanUtil as u

img1 = cv.imread('../data/ml.png')
img2 = cv.imread('../data/opencv-logo.png')

img1 = cv.resize(img1, (500, 500), interpolation = cv.INTER_CUBIC)
img2 = cv.resize(img2, (500, 500), interpolation = cv.INTER_CUBIC)

for i in range(1, 101, 1):
    cv.imshow('result', cv.addWeighted(img2, 0 + (i / 100), img1, 1 - (i / 100), 0) )
    cv.waitKey(10)
    
cv.destroyAllWindows()
cv.waitKey(1)


-1