### OpenCV의 윤곽
All about Contours in OpenCV

#### 윤곽선 : 시작하기
Learn to find and draw Contours

##### 목표
* 윤곽선이 무엇인지 이해하십시오.
* 등고선 찾기, 등고선 그리기 등을 배우십시오.
* 다음 함수를 볼 수 있습니다 : cv.findContours () , cv.drawContours ()

##### 윤곽석인란 무었인가
윤곽선은 동일한 색상이나 강도를 가진 모든 연속 점 (경계를 따라)을 결합하는 곡선으로 간단히 설명 할 수 있습니다. 윤곽선은 형상 분석 및 객체 감지 및 인식에 유용한 도구입니다.

* 정확성을 높이려면 이진 이미지를 사용하십시오. 따라서 윤곽선을 찾기 전에 임계점 또는 캐니 에지 감지를 적용하십시오.
* OpenCV 3.2부터 findContours () 는 더 이상 원본 이미지를 수정하지 않지만 수정 된 이미지를 세 개의 반환 매개 변수 중 첫 번째로 반환합니다.
* OpenCV에서 윤곽선을 찾는 것은 검정색 배경에서 흰색 물체를 찾는 것과 같습니다. 그러므로 찾을 수있는 물체는 흰색이어야하고 배경은 검은 색이어야합니다.

이진 이미지의 윤곽선을 찾는 방법을 살펴 보겠습니다.

In [7]:
import numpy as np
import cv2 as cv
import bonghanUtil as util

im = cv.imread('test.png')
imgray = cv.cvtColor(im, cv.COLOR_BGR2GRAY)

ret, thresh = cv.threshold(imgray, 127, 255, 0)
im2, contours, hierarchy = cv.findContours(thresh, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)

See, cv.findContours () 함수 에는 세 개의 인수가 있습니다. 첫 번째는 소스 이미지이고, 두 번째는 등고선 검색 모드이고, 세 번째는 등고선 근사 방법입니다. 그리고 수정 된 이미지, 등고선 및 계층 구조를 출력합니다. 윤곽은 이미지의 모든 윤곽을 파이썬으로 나타낸 목록입니다. 각각의 개별 윤곽은 객체의 경계 지점의 (x, y) 좌표의 넘파이 배열입니다.

##### How to draw the contours?
윤곽선을 그리려면 cv.drawContours 함수가 사용됩니다. 또한 경계 지점이있는 경우 모든 모양을 그리는 데 사용할 수 있습니다. 첫 번째 인수는 소스 이미지이고, 두 번째 인수는 파이썬 목록으로 전달되어야하는 등고선이며, 세 번째 인수는 등고선 색인입니다 (개별 윤곽선을 그리는 데 유용합니다. 모든 윤곽선을 그리려면 -1을 전달하고 나머지 인수는 색상, 두께 기타

* To draw all the contours in an image:

In [6]:
img = np.zeros(im.shape, np.uint8)

resultImg = cv.drawContours(img, contours, -1, (0,255,0), 3)

util.showImage(resultImg)

* To draw an individual contour, say 1st contour:

In [17]:
img = np.zeros(im.shape, np.uint8)
resultImg = cv.drawContours(img, contours, 2nd, (0,255,0), 1)

util.showImage(resultImg)

* But most of the time, below method will be useful:

In [19]:
img = np.zeros(im.shape, np.uint8)
cnt = contours[2]
resultImg = cv.drawContours(img, [cnt], 0, (0,255,0), 3)
util.showImage(resultImg)

* 결과
![](contour_01.png '이미지')

array([[[ 16,  22]], [[ 16, 147]], [[205, 147]], [[205,  22]]], dtype=int32)

![](contour_02.png)
array([[[ 57,  59]], [[ 58,  58]], [[161,  58]], [[162,  59]],  
       [[162, 105]], [[161, 106]], [[ 58, 106]], [[ 57, 105]]], dtype=int32)

![](contour_03.png)
array([[[ 91,  70]], [[ 91,  95]], [[133,  95]], [[133,  70]]], dtype=int32)


##### 윤곽선 근사 방법

이것은 cv.findContours 함수 의 세 번째 인수입니다 . 실제로 그것이 무엇을 나타내는가?

위에서 우리는 등고선이 동일한 강도를 지닌 모양의 경계라고 말했다. 도형 경계의 (x, y) 좌표를 저장합니다. 그러나 그것은 모든 좌표를 저장합니까? 이것은이 윤곽 근사법으로 지정됩니다.

**cv.CHAIN_APPROX_NONE** 를 건네 주면 모든 경계 지점이 저장됩니다. 그러나 실제로 모든 포인트가 필요합니까? 예를 들어, 직선의 윤곽을 발견했습니다. 그 라인을 나타 내기 위해 라인의 모든 포인트가 필요합니까? 아니요, 우리는 그 라인의 두 종점 만 있으면됩니다. 이것이 **cv.CHAIN_APPROX_SIMPLE**의 기능 입니다. 모든 중복 점을 제거하고 윤곽을 압축하여 메모리를 절약합니다.

아래의 사각형 이미지는이 기법을 보여줍니다. 윤곽선 배열의 모든 좌표에 원을 그립니다 (파란색으로 그려 짐). 첫 번째 이미지는 cv.CHAIN_APPROX_NONE (734 점)으로 얻은 점을 표시 하고 두 번째 이미지는 cv.CHAIN_APPROX_SIMPLE (4 점 만)으로 표시합니다. 얼마나 많은 메모리가 절약되는지보십시오!


In [32]:
for contour in contours:
    print('cv.CHAIN_APPROX_SIMPLE 점의 개수', len(contour))

im2, contours, hierarchy = cv.findContours(thresh, cv.RETR_TREE, cv.CHAIN_APPROX_NONE)

for contour in contours:
    print('cv.CHAIN_APPROX_NONE 점의 개수', len(contour))

cv.CHAIN_APPROX_SIMPLE 점의 개수 4
cv.CHAIN_APPROX_SIMPLE 점의 개수 8
cv.CHAIN_APPROX_SIMPLE 점의 개수 4
cv.CHAIN_APPROX_NONE 점의 개수 628
cv.CHAIN_APPROX_NONE 점의 개수 302
cv.CHAIN_APPROX_NONE 점의 개수 134


#### 윤관선 특징
Learn to find different features of contours like area, perimeter, bounding rectangle etc.

##### 목표
In this article, we will learn

To find the different features of contours, like area, perimeter, centroid, bounding box etc
You will see plenty of functions related to contours.

##### 1. Moments
이미지 순간은 물체의 중심, 물체의 면적 등과 같은 일부 기능을 계산하는 데 도움이됩니다. 이미지 순간 에 위키 백과 페이지를 확인하십시오.

함수 cv.moments () 는 모든 모멘트 값의 사전을 계산합니다. 아래 참조 :


In [2]:
import numpy as np
import cv2 as cv
import bonghanUtil as util

im = cv.imread('star.png')
imgray = cv.cvtColor(im, cv.COLOR_BGR2GRAY)

ret, thresh = cv.threshold(imgray, 127, 255, 0)
im2, contours, hierarchy = cv.findContours(thresh, 1, 2)

cnt = contours[0]
M = cv.moments(cnt)

img = np.zeros(im.shape, np.uint8)
resultImg = cv.drawContours(img, [cnt], 0, (0,255,0), 1)

print(M)
util.showImage(resultImg)

'''
import numpy as np
import cv2 as cv
import bonghanUtil as util

im = cv.imread('test.png')
imgray = cv.cvtColor(im, cv.COLOR_BGR2GRAY)

ret, thresh = cv.threshold(imgray, 127, 255, 0)
im2, contours, hierarchy = cv.findContours(thresh, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)

#cnt = contours[0]
#M = cv.moments(cnt)

bImg = np.zeros(im2.shape, np.uint8)
resultImg = cv.drawContours(bImg, contours, -1, (0, 255, 0), 3)

util.showImage(resultImg)
#print(M)
'''

{'m00': 20612.5, 'm10': 2132893.833333333, 'm01': 1547028.6666666665, 'm20': 278538862.4166666, 'm11': 161127680.4583333, 'm02': 140876415.25, 'm30': 40728463295.15, 'm21': 21199448440.9, 'm12': 14743092154.3, 'm03': 14334760462.7, 'mu20': 57836079.917146444, 'mu11': 1047733.672488749, 'mu02': 24767369.986764386, 'mu30': -62816675.30971527, 'mu21': 77458662.01050472, 'mu12': 8528884.363070488, 'mu03': 43844000.16923523, 'nu20': 0.13612488060637562, 'nu11': 0.0024659800816225035, 'nu02': 0.05829328832818613, 'nu30': -0.0010297890633591677, 'nu21': 0.0012698233806161868, 'nu12': 0.0001398187948731924, 'nu03': 0.000718759336523068}


"\nimport numpy as np\nimport cv2 as cv\nimport bonghanUtil as util\n\nim = cv.imread('test.png')\nimgray = cv.cvtColor(im, cv.COLOR_BGR2GRAY)\n\nret, thresh = cv.threshold(imgray, 127, 255, 0)\nim2, contours, hierarchy = cv.findContours(thresh, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)\n\n#cnt = contours[0]\n#M = cv.moments(cnt)\n\nbImg = np.zeros(im2.shape, np.uint8)\nresultImg = cv.drawContours(bImg, contours, -1, (0, 255, 0), 3)\n\nutil.showImage(resultImg)\n#print(M)\n"

From this moments, you can extract useful data like area, centroid etc. Centroid is given by the relations, Cx = M10 / M00 and Cy = M01 / M00. This can be done as follows:

In [3]:
cx = int(M['m10'] / M['m00'])
cy = int(M['m01'] / M['m00'])

print(img.shape, cx, cy)
#util.showImage(img)

(149, 204, 3) 103 75


##### 2. Contour Area
Contour area is given by the function cv.contourArea() or from moments, M['m00'].

In [21]:
area = cv.contourArea(cnt)

print(area)


20612.5


##### 3. Contour Perimeter
아크 길이라고도합니다. cv.arcLength () 함수를 사용하여 찾을 수 있습니다 . 두 번째 인수는 모양이 닫힌 윤곽 (True로 전달 된 경우)인지 또는 곡선인지 지정합니다.

In [4]:
perimeter = cv.arcLength(cnt, True)

print(perimeter)

938.4924212694168


##### 4. Contour Approximation
우리가 지정한 정밀도에 따라 윤곽 셰이프를 정점 수가 적은 다른 모양으로 근사합니다. Douglas-Peucker 알고리즘을 구현 한 것입니다 . 위키 백과 페이지에서 알고리즘 및 데모를 확인하십시오.

이를 이해하기 위해 이미지에서 사각형을 찾으려고했지만 이미지의 일부 문제로 인해 완벽한 사각형이 아니라 "나쁜 모양"(아래 첫 번째 그림 참조)을 얻었습니다. 이제이 함수를 사용하여 모양을 근사시킬 수 있습니다. 이 두 번째 인수는 엡실론 (epsilon)이라고하며, 이것은 윤곽선에서 근사화 된 윤곽선까지의 최대 거리입니다. 이것은 정확도 매개 변수입니다. 올바른 출력을 얻으려면 엡실론을 현명하게 선택해야합니다.

In [9]:
epsilon = 0.1 * cv.arcLength(cnt, True)
approx = cv.approxPolyDP(cnt, epsilon, True)

img = np.zeros(im.shape, np.uint8)
resultImg = cv.drawContours(img, [cnt], 0, (0,255,0), 1)

util.showImage(resultImg)

resultImg = cv.drawContours(img, [approx], 0, (0,255,0), 1)

util.showImage(resultImg)

print(epsilon, approx)

93.84924212694169 [[[ 11  15]]

 [[ 11 138]]

 [[194 138]]

 [[194  15]]]


##### 5. Convex Hull

##### 6. Checking Convexity

##### 7. Bounding Rectangle

##### 8. Minimum Enclosing Circle

##### 9. Fitting an Ellipse

##### 10. Fitting a Line